### ISSUE TITLE
Set up publish action

### ISSUE THREAD

**Issue by jhossbach** [python-lsp/python-lsp-ruff#23]
Continuation from the conversation in #22 
Actions intended for publishing for 
 - PyPi
 - Anaconda

For PyPi there is a Github Action that we can use. For that I would like to change the ownership of the Pypi package to the python lsp project. Then we can store the credentials for the pylsp Pypi account in Github to be used as action. Can we do this @ccordoba12?

**Comment by ccordoba12** [comment]
> For PyPi there is a Github Action that we can use. For that I would like to change the ownership of the Pypi package to the python lsp project

We don't have an account for the project on PyPI and I haven't seen project accounts for other, important projects, for instance:

* https://pypi.org/project/matplotlib
* https://pypi.org/project/numpy

So, I'd prefer each project in our organization to handle its own credentials. That would be safer too because if a project's credentials are compromised somehow, it wouldn't affect the entire organization.

**Comment by jhossbach** [comment]
Hmm, in that case I'd rather not expose any credentials to GitHub. I expect the codebase not to increase a lot in the future anyways so a publish action is probably going to be unnecessary.
