### ISSUE TITLE
Ruff.toml support

### ISSUE THREAD

**Issue by KhazAkar** [python-lsp/python-lsp-ruff#28]
Hi,
Is config option for this project also applies for ruff.toml or only for pyproject.toml? If not, is it possible to have possibility to pass ruff.toml instead of pyproject.toml?

**Comment by jhossbach** [comment]
If a `pyproject.toml` (and currently only that) is present most of the config options that you give via `pylsp` are ignored.
We can extend this behavior to do the same if a `ruff.toml` is present.

This also means that we have to check if a `pyproject.toml` file actually contains `[tool.ruff]` and otherwise ignore it.
Thanks for the clue!

**Comment by KhazAkar** [comment]
You're welcome, glad that helped :)
I'll keep this issue open for implementation of mentioned support & enhacement for handling pyproject.toml ;)
